
GET http://localhost:3000/user 
### 
GET http://localhost:3000/user/63c9629eae95064f8aac80bc

### 
GET http://localhost:3000/contacts/63c9629eae95064f8aac80bd

### 
POST http://localhost:3000/user HTTP/1.1 
Content-type: application/json

{
    "firstName":"jacob",
    "lastName":"Oliveira",
    "userName":"lucoli",
    "password":"asdfgh",
    "email":"luc@example.com",
    "phoneNumber":"333-333-333",
    "country":"Brasil",
    "goals":[
        {
            "goalName":"create an account",
            "startDate":"01-01-2023",
            "endDate":"03-15-2023",
            "plan":"get visa"
          
        },{
            "goalName":"Start collage",
            "startDate":"01-01-2023",
            "endDate":"06-01-2023",
            "plan":"study for the exam"
        }
      ]   
}

###
PUT http://localhost:3000/user/dsfsdfsdf HTTP/1.1 
Content-type: application/json

{
    "firstName":"jacob",
    "lastName":"Oliveira",
    "userName":"lucoli35",
    "password":"asdfgh",
    "email":"luc@example.com",
    "phoneNumber":"333-333-333",
    "country":"Brasil",
    "goals":[
        {
            "goalName":"create an account",
            "startDate":"01-01-2023",
            "endDate":"03-15-2023",
            "plan":"get visa"
          
        },{
            "goalName":"Start collage",
            "startDate":"01-01-2023",
            "endDate":"06-01-2023",
            "plan":"study for the exam"
        }
      ]   
}

### 
DELETE http://localhost:3000/user/63c9cc54ecac4b74c25a06da

###
GET https://cse341-project-2.onrender.com/user 
### 
GET https://cse341-project-2.onrender.com/user/63c9629eae95064f8aac80bc

### 
GET https://cse341-project-2.onrender.com/contacts/63c9629eae95064f8aac80bd

### 
POST https://cse341-project-2.onrender.com/user HTTP/1.1 
Content-type: application/json

{
    "firstName":"Lucas",
    "lastName":"Oliveira",
    "userName":"lucoli",
    "password":"asdfg",
    "email":"luc@example.com",
    "phoneNumber":"333-333-333",
    "country":"Brasil",
    "goals":[
        {
            "goalName":"travel to USA",
            "startDate":"01-01-2023",
            "endDate":"03-15-2023",
            "plan":"get visa"
          
        },{
            "goalName":"Start collage",
            "startDate":"01-01-2023",
            "endDate":"06-01-2023",
            "plan":"study for the exam"
        }
      ]   
}
###
PUT https://cse341-project-2.onrender.com/user/63cb5526a7 HTTP/1.1 
Content-type: application/json

{
    "firstName":"jacob",
    "lastName":"Oliveira",
    "userName":"lucoli35",
    "password":"asdfgh",
    "email":"luc@example.com",
    "phoneNumber":"333-333-333",
    "country":"Brasil",
    "goals":[
        {
            "goalName":"create an account",
            "startDate":"01-01-2023",
            "endDate":"03-15-2023",
            "plan":"get visa"
          
        },{
            "goalName":"Start collage",
            "startDate":"01-01-2023",
            "endDate":"06-01-2023",
            "plan":"study for the exam"
        }
      ]   
}

### 
DELETE https://cse341-project-2.onrender.com/user/63c9cc54ecac4b74c25a06da